application: pagifyapp
version: 1-0
runtime: python
api_version: 1

skip_files: |
 ^(.*/)?(
 (app\.yaml)|
 (app\.yml)|
 (index\.yaml)|
 (index\.yml)|
 (#.*#)|
 (.*~)|
 (.*\.py[co])|
 (.*\.DS_Store)|
 (.*\.git)|
 (.*\.gitignore)|
 (.*/Crypto/.*)|
 (.*/src/.*) 
 )$

builtins:
- remote_api: on
- datastore_admin: on
- deferred: on
- appstats: off

handlers:
- url: /_ah/warmup
  script: main.py

- url: /_ereporter.*
  script: $PYTHON_LIB/google/appengine/ext/ereporter/report_generator.py
  login: admin

- url: /(robots\.txt|favicon\.ico|apple-touch-icon\.png)
  static_files: static/\1
  upload: static/.*
  
- url: /static
  static_dir: static

- url: /.*
  script: main.py
  
admin_console:
  pages:
  - name: Appstats
    url: /_ah/stats/
  - name: Admin Utilities
    url: /admin
  
error_handlers:
- file: /templates/errors/default_gae_error.html
